"""initial schema

Revision ID: f9dfb20755b4
Revises: 
Create Date: 2026-05-16 11:34:05.899009

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dfb20755b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), server_default='apprise', nullable=False),
    sa.Column('apprise_url_blob', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_channels_name'), ['name'], unique=True)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), server_default='0.0.0', nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('homepage', sa.String(length=256), nullable=True),
    sa.Column('default_cron', sa.String(length=64), nullable=True),
    sa.Column('default_timeout_sec', sa.Integer(), server_default='300', nullable=False),
    sa.Column('fields_schema_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('requires_secret', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('manifest_path', sa.String(length=512), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scripts_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_scripts_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('cron_expr', sa.String(length=64), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_blob', sa.Text(), server_default='', nullable=False),
    sa.Column('config_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_interval_sec', sa.Integer(), server_default='60', nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('last_run_status', sa.String(length=16), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_successes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], name='fk_instances_last_run_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index('ix_instances_script_enabled', ['script_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_script_id'), ['script_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_secret', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('min_interval_sec', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_rules_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_rules_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_rules_script_id'), ['script_id'], unique=False)
        batch_op.create_index('ix_rules_scope_lookup', ['scope', 'script_id', 'instance_id', 'event', 'enabled'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('script_slug', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_user_id', sa.Integer(), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('result_message', sa.String(length=512), nullable=True),
    sa.Column('result_data_json', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('stdout_truncated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('stderr_truncated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['trigger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_instance_started', ['instance_id', 'started_at'], unique=False)
        batch_op.create_index('ix_runs_script_started', ['script_slug', 'started_at'], unique=False)
        batch_op.create_index('ix_runs_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_runs_status_started', ['status', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status_started')
        batch_op.drop_index('ix_runs_started_at')
        batch_op.drop_index('ix_runs_script_started')
        batch_op.drop_index('ix_runs_instance_started')

    op.drop_table('runs')
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_rules_scope_lookup')
        batch_op.drop_index(batch_op.f('ix_notification_rules_script_id'))
        batch_op.drop_index(batch_op.f('ix_notification_rules_instance_id'))
        batch_op.drop_index(batch_op.f('ix_notification_rules_channel_id'))

    op.drop_table('notification_rules')
    op.drop_table('settings')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token'))

    op.drop_table('sessions')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_script_id'))
        batch_op.drop_index('ix_instances_script_enabled')
        batch_op.drop_index(batch_op.f('ix_instances_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_instances_enabled'))

    op.drop_table('instances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scripts_slug'))
        batch_op.drop_index(batch_op.f('ix_scripts_enabled'))

    op.drop_table('scripts')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_name'))
        batch_op.drop_index(batch_op.f('ix_notification_channels_enabled'))

    op.drop_table('notification_channels')
    # ### end Alembic commands ###
